import { writeFileSync, mkdirSync } from 'fs'
import { join } from 'path'
import type { Plugin } from '../plugins.js'
import type { Config } from '../config.js'
import type { Page } from '../page.js'

export const tagsPlugin: Plugin = {
  name: 'tags',
  on_post_build(config) {
    const tagsDir = join(config.site_dir, 'tags')
    mkdirSync(tagsDir, { recursive: true })
    writeFileSync(
      join(tagsDir, 'index.html'),
      `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Tags - ${config.site_name}</title></head><body><h1>Tags</h1><p>Tag index generated by ts-mkdocs tags plugin.</p></body></html>`,
    )
  },
  on_page_content(html, page) {
    const tags = page.meta.tags as string[] | undefined
    if (!tags?.length) return html
    const tagHtml = tags.map((t) => `<span class="md-tag">${t}</span>`).join(' ')
    return `<div class="md-tags">${tagHtml}</div>\n${html}`
  },
}
