import { mkdirSync, writeFileSync } from 'fs'
import { join } from 'path'
import type { Plugin } from '../plugins.js'

export const tagsPlugin: Plugin = {
  name: 'tags',
  on_post_build(config) {
    const tagsDir = join(config.site_dir, 'tags')
    mkdirSync(tagsDir, { recursive: true })
    writeFileSync(
      join(tagsDir, 'index.html'),
      `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Tags - ${config.site_name}</title></head><body><h1>Tags</h1><p>Tag index generated by ts-mkdocs tags plugin.</p></body></html>`,
    )
  },
}
